var THREE;
THREE.REVISION;
THREE.Scene;
THREE.PerspectiveCamera;
THREE.WebGLRenderer;
THREE.BoxGeometry;
THREE.MeshBasicMaterial;
THREE.Mesh;
THREE.GridHelper;
THREE.AxesHelper;
THREE.DirectionalLight;
THREE.TorusGeometry;
THREE.MeshStandardMaterial;
THREE.Mesh;
THREE.PlaneGeometry;
THREE.Fog;
